/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //if(args[1] == "0") {
            SQSRecieve.receive("https://sqs.us-west-2.amazonaws.com/074808275502/QueueA");
        //}
        //else{
           // SQSSend.send(args[0]);
        //}
    }
}
